source("R/is_nn.R")
#' @title hid
#'
#' @description The function that returns the number of hidden layers of a
#' neural network. Denoted \eqn{\mathsf{H}}
#'
#' @param nu a neural network of the type generated by create_neural_network()
#'
#' By definition \eqn{\mathsf{H}(\nu) = \mathsf{D}(\nu) - 1}
#'
#' @references Definition 1.3.1. Jentzen, A., Kuckuck, B., and von Wurstemberger, P. (2023).
#' Mathematical introduction to deep learning: Methods, implementations,
#' and theory. \url{https://arxiv.org/abs/2310.20360}.
#'
#' @return Integer representing the number of hidden layers.
#' @export

hid <- function(nu) {
  if (nu |> is_nn() == TRUE) {
    return(length(nu) - 1)
  } else {
    stop("Only neural networks can have hidden layers")
  }
}

#' @title dep
#' @description The function that returns the depth of a neural network. Denoted
#' \eqn{\mathsf{D}}.
#'
#' @param nu a neural network of the type generated by
#' create_neural_network(). Very straightforwardly it is the
#' length of the list where neural networks are defined as an odered list of
#' lists.
#' @references Definition 1.3.1. Jentzen, A., Kuckuck, B., and von Wurstemberger, P. (2023).
#' Mathematical introduction to deep learning: Methods, implementations,
#' and theory. \url{https://arxiv.org/abs/2310.20360}.
#'
#' @return Integer representing the depth of the neural network.
#' @export

dep <- function(nu) {
  if (nu |> is_nn() == TRUE) {
    return(length(nu))
  } else {
    stop("Only neural networks can have depth")
  }
}

#' @title inn
#' @description The function that returns the input layer size of a neural
#' network. Denoted \eqn{\mathsf{I}}
#'
#' @param nu A neural network of the type generated by
#' create_neural_network().
#'
#' @references Definition 1.3.1. Jentzen, A., Kuckuck, B., and von Wurstemberger, P. (2023).
#' Mathematical introduction to deep learning: Methods, implementations,
#' and theory. \url{https://arxiv.org/abs/2310.20360}.
#'
#' @return An integer representing the input width of the neural network.
#' @export

inn <- function(nu) {
  if (nu |> is_nn() == TRUE) {
    return(dim(nu[[1]]$W)[2])
  } else {
    stop("Only neural networks can have size of input layers")
  }
}


#' @title out
#' @description The function that returns the output layer size of a neural
#' network. Denoted \eqn{\mathsf{O}}.
#'
#' @param nu A neural network of the type generated by create_neural_network().
#'
#' @references Definition 1.3.1. Jentzen, A., Kuckuck, B., and von Wurstemberger, P. (2023).
#' Mathematical introduction to deep learning: Methods, implementations,
#' and theory. \url{https://arxiv.org/abs/2310.20360}.
#'
#' @return An integer representing the output width of the neural network.
#' @export

out <- function(nu) {
  if (nu |> is_nn() == TRUE) {
    return(dim(nu[[length(nu)]]$W)[1])
  } else {
    stop("Ony neural networks can have size of output layers")
  }
}


#' @title lay
#' @description The function that returns the layer architecture of a neural
#' network.
#'
#' @param nu A neural network of the type generated by
#' create_neural_network(). Denoted \eqn{\mathsf{L}}.
#'
#' @references Definition 1.3.1. Jentzen, A., Kuckuck, B., and von Wurstemberger, P. (2023).
#' Mathematical introduction to deep learning: Methods, implementations,
#' and theory. \url{https://arxiv.org/abs/2310.20360}.
#'
#' @return A tuple representing the layer architecture of our neural network.
#' @export

lay <- function(nu) {
  if (nu |> is_nn() == TRUE) {
    layer_architecture <- list()
    for (i in 1:length(nu)) {
      layer_architecture |> append(dim(nu[[i]]$W)[1]) -> layer_architecture
    }
    inn(nu) |> append(layer_architecture) -> layer_architecture
    return(layer_architecture)
  } else {
    stop("Only neural networks can have layer architectures")
  }
}


#' @title param
#' @description The function that returns the numbe of parameters of a neural
#' network.
#'
#' @param nu A neural network of the type generated by
#' create_neural_network(). Denoted \eqn{\mathsf{P}}.
#'
#' @references Definition 1.3.1. Jentzen, A., Kuckuck, B., and von Wurstemberger, P. (2023).
#' Mathematical introduction to deep learning: Methods, implementations,
#' and theory. \url{https://arxiv.org/abs/2310.20360}.
#'
#' @return An integer representing the parameter count of our neural network.
#' @export

param <- function(nu) {
  if (nu |> is_nn() == TRUE) {
    0 -> param_count
    for (i in 1:length(nu)) {
      param_count + length(nu[[i]]$W) + length(nu[[i]]$b) -> param_count
    }
    return(param_count)
  } else {
    stop("Only neural networks can have parameters")
  }
}
