source("R/comp.R")
source("R/stacking.R")
source("R/aux_fun.R")
source("R/Aff.R")
source("R/is_nn.R")

#' @title nn_sum
#' @description A function that performs the neural network sum for two
#' neural networks of the type generated by
#' create_neural_network(). Neural network sums are defined for
#' \eqn{\nu_1 \in \mathsf{NN}} and \eqn{\nu_2 \in \mathsf{NN}} as:
#' \deqn{
#' \oplus^v_{i=u}\nu_i \coloneqq \left( \mathsf{Sum}_{v-u+1,\mathsf{O}(\nu_2)} \bullet \left[ \boxminus^v_{i=u}\nu_i \right] \bullet \mathsf{Cpy}_{(v-u+1),\mathsf{I}(\nu_1)} \right)
#' }
#'
#' @references Grohs, P., Hornung, F., Jentzen, A. et al.
#' Space-time error estimates for deep neural network approximations
#' for differential equations. Adv Comput Math 49, 4 (2023).
#' \url{https://doi.org/10.1007/s10444-022-09970-2}.
#'
#' @param nu_1 A neural network.
#' @param nu_2 A neural network.
#'
#' @return A neural network that is the neural network sum of \eqn{\nu_1} and \eqn{\nu_2}
#' i.e. \eqn{\nu_1 \oplus \nu_2}.
#'
#' \emph{Note:} We have two versions, an infix version and a prefix version.
#' @export

nn_sum <- function(nu_1, nu_2) {
  if (nu_1 |> is_nn() &&
    nu_2 |> is_nn() &&
    inn(nu_1) == inn(nu_2) &&
    out(nu_1) == out(nu_2)) {
    Cpy(2, inn(nu_1)) -> first_third
    nu_1 |> stk(nu_2) -> mid_third
    Sum(2, out(nu_1)) -> last_third

    last_third |>
      comp(mid_third) |>
      comp(first_third) -> return_network
    return(return_network)
  } else {
    stop("Only neural networks with same end-widths may be summed")
  }
}

#' Function for calculating neural network sums
#'
#' @param nu_1 A neural network.
#' @param nu_2 A neural network.
#'
#' @rdname nn_sum
#' @export
#'
`%nn_sum%` <- function(nu_1, nu_2) {
  if (nu_1 |> is_nn() &&
    nu_2 |> is_nn() &&
    inn(nu_1) == inn(nu_2) &&
    out(nu_1) == out(nu_2)) {
    Cpy(2, inn(nu_1)) -> first_third
    nu_1 |> stk(nu_2) -> mid_third
    Sum(2, out(nu_1)) -> last_third

    last_third |>
      comp(mid_third) |>
      comp(first_third) -> return_network
    return(return_network)
  } else {
    stop("Only neural networks of same end widths may be summed")
  }
}
